apiVersion: batch/v1
kind: Job
metadata:
  name: zeno-habit-e2e-job
  labels:
    app: zeno-habit-e2e
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: zeno-habit-e2e
        image: zeno15/zeno-habit-e2e:$E2E_IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: CYPRESS_WEB_URL
          value: 'https://habit-web-dev.markdavison.kiwi/'
        - name: CYPRESS_BFF_URL
          value: 'https://habit-bff-dev.markdavison.kiwi/'
