apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.app}}-dep
  labels:
    app: {{ .Values.api.app }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app:  {{ .Values.api.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.app }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.api.port }}
        env:
        {{- include "helpers.list-api-deployment-env-variables" . | indent 10 }}
